config/routes.rb
Rails.application.routes.draw do
  resources :reservations, except: [:show]
  get 'reservations/:id/note', to: 'reservations#note', as: 'note_reservation'
  match 'reservations/check' => 'reservations#check', via: [:get, :post]

  resources :tables, only: [:index, :create, :update, :destroy]
  get 'tables/restrict' => 'tables#restrict'

  devise_for :users
  get 'users', to: 'users#index', as: 'users'
  post 'create_user', to: 'users#create', as: 'create_user'
  delete 'destroy_user/:id', to: 'users#destroy', as: 'destroy_user'
  post 'promote_user/:id', to: 'users#promote', as: 'promote_user'

  get 'reservations', to: 'reservations#index', as: 'user_root'
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  get '*path' => redirect('/')

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %w(manager employee).freeze

  before_create :set_default_role

  def roles=(roles)
    self.roles_mask = (Array(roles) & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end

  ROLES.each do |role|
    define_method "#{role}?" do
      roles.include? role
    end
  end

  private

  def set_default_role
    return if manager? || employee?
    self.roles = 'employee'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_manager!, except: [:edit, :update]
  before_action :set_user, only: [:edit, :update, :destroy, :promote]
  skip_before_action :require_no_authentication

  def index
    @users = User.all

    @user = User.new
    respond_to { |format| format.html }
  end

  def create
    user = User.new(user_params)

    if user.save
      flash[:notice] = 'Utworzono nowego pracownika'
    else
      flash[:alert] = 'Wystąpił błąd podczas zapisu'
    end

    respond_to do |format|
      format.html { redirect_to users_path }
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = 'Pomyślnie usunięto użytkownika'
    else
      flash[:alert] = 'Wystąpił błąd podczas usuwania'
    end

    respond_to do |format|
      format.html { redirect_to users_path }
    end
  end

  def promote
    @user.roles = 'manager'

    if @user.save
      flash[:notice] = 'Awansowano użytkownika na managera'
    else
      flash[:alert] = 'Wystąpił błąd podczas zapisu'
    end
    respond_to do |format|
      format.html { redirect_to users_path }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def humanize_role(role)
    case role
    when 'manager' then t('users.roles.manager')
    when 'employee' then t('users.roles.employee')
    end
  end
end

app/views/users/index.html.haml
#container
  .panel.panel-primary
    .panel-heading
      .panel-title= t('.manage')
    %table.table.table-striped
      %thead
        %tr
          %th= t('.email')
          %th= t('.role')
          %th= t('all.manage')
      %tbody
        - @users.each do |user|
          %tr
            %td= user.email
            %td= humanize_role(user.roles.first)
            %td
              - if can?(:update, user) && !user.manager?
                = link_to glyph('', 'arrow-up'), promote_user_path(user.id), class: 'promote-user', method: :post, title: t('.promote')
              - if can? :destroy, user
                = link_to glyph('', 'remove'), destroy_user_path(user.id), class: 'remove-user', method: :delete, title: t('.delete'), data: { confirm: t('all.sure') }

%h2= t('.add_new')

= form_for @user, url: create_user_url do |f|
  - if f.object.errors.any?
    - f.object.errors.full_messages.each do |msg|
      .alert.alert-danger.col-xs-12= msg
  .form-group.col-xs-12
  .col-md-3
    .input-group
      .input-group-addon= f.label :email, t('.email')
      = f.text_field :email, class: 'form-control'
  .form-group.col-xs-12.col-md-3
    .input-group
      .input-group-addon= f.label :password, t('.password')
      = f.password_field :password, class: 'form-control'
  .form-group.col-xs-12.col-md-4
    .input-group
      .input-group-addon= f.label :password_confirmation, t('.password_confirmation')
      = f.password_field :password_confirmation, min: 1, class: 'form-control'
  .form-group.col-xs-12.col-md-2
    = f.submit t('.submit'), class: 'btn btn-success btn-block'