config/routes.rb
Rails.application.routes.draw do
  resources :reservations, except: [:show]
  get 'reservations/:id/note', to: 'reservations#note', as: 'note_reservation'
  match 'reservations/check' => 'reservations#check', via: [:get, :post]

  resources :tables, only: [:index, :create, :update, :destroy]
  get 'tables/restrict' => 'tables#restrict'

  devise_for :users
  get 'users', to: 'users#index', as: 'users'
  post 'create_user', to: 'users#create', as: 'create_user'
  delete 'destroy_user/:id', to: 'users#destroy', as: 'destroy_user'
  post 'promote_user/:id', to: 'users#promote', as: 'promote_user'

  get 'reservations', to: 'reservations#index', as: 'user_root'
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  get '*path' => redirect('/')

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  acts_as_paranoid column: :cancelled_at
  belongs_to :table

  validates :table_id, :date, :hour, :client_name, :client_phone, :people,
            presence: true
  validates :table_id, numericality: true, inclusion: { in: Table.ids }
  validates :table_id, uniqueness: {
    scope: :date
  }
  validate :table_have_enough_seats
  validate :date_cant_be_past
  validates :hour, format: {
    with: /\A\d{1,2}.\d{2}\z/
  }
  validates :people, numericality: { only_integer: true, greater_than: 0 }
  validates :client_phone, format: {
    with: /\A\d{9}\z/
  }

  before_save :correct_hour
  after_create :send_sms

  scope :current, -> { where('date >= ?', Time.current.beginning_of_day) }
  scope :old, -> { where('date < ?', Time.current.beginning_of_day) }

  def send_sms
    return unless approved?
    return unless client_phone == '669215504'
    service = SmsAPI::Service.new(client_phone)
    service.message = I18n::t('.reservations.approved', day: date, hour: hour)
    service.send_sms
  end

  private

  def correct_hour
    h = hour.scan(/(\d+).(\d+)/).flatten
    h[0] = "0#{h[0]}" if h[0].length == 1
    self.hour = h.join(':')
  end

  def date_cant_be_past
    return if date.nil?
    if date < Time.current.beginning_of_day
      errors.add(:date, "can't be in the past")
    end
  end

  def table_have_enough_seats
    return if people.nil?
    seats = Table.find(table_id).seats.to_i
    errors.add(:table_id, "doesn't have enough seats") if seats < people
  rescue ActiveRecord::RecordNotFound
    errors.add(:table_id, "doesn't exist")
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :check]
  before_action :set_reservation, only: [:edit, :update, :destroy, :note]

  def index
    @reservations = params[:old] ? Reservation.old : Reservation.current
    @reservations = @reservations.with_deleted if can? :manage, Reservation
    @reservations = @reservations.order(order_clause).group_by(&:date)

    respond_to { |format| format.html }
  end

  def new
    @r = Reservation.new
    @tables = Table.all.pluck(:id, :number)

    respond_to { |format| format.html }
  end

  def create
    @r = Reservation.new(reservation_params)
    Rails.logger.error reservation_params.inspect
    Rails.logger.error params.inspect
    respond_to do |format|
      if @r.save
        flash[:notice] = t('.reserved', nr: @r.table.number, day: @r.date, hour: @r.hour)
        format.html { redirect_to(user_signed_in? ? reservations_path : reservations_check_path) }
      else
        @tables = Table.all.pluck(:id, :number)
        format.html { render :new }
      end
    end
  end

  def edit
    respond_to { |format| format.html }
  end

  def update
    approved_then = @r.approved
    @r.assign_attributes(reservation_params)

    respond_to do |format|
      if @r.save
        flash[:notice] = t('.updated')
        @r.send_sms if !approved_then && @r.approved
        format.html { redirect_to reservations_path }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    redirect_to(:back, alert: t('.reason_empty')) && return if params[:note].blank?

    @r.update_attributes(cancel_reason: params[:note])

    respond_to do |format|
      if @r.destroy
        format.html { redirect_to reservations_path, notice: t('.success') }
      else
        format.html { redirect_to :back, alert: t('.error') }
      end
    end
  end

  def note
    respond_to { |format| format.html }
  end

  def check
    if request.post?
      @r = Reservation.current.where(
        client_name: params[:client_name],
        client_phone: params[:client_phone]
      )
    end

    respond_to { |format| format.html }
  end

  private

  def reservation_params
    params.require(:reservation).permit(
      :date, :hour, :client_phone, :client_name, :people, :table_id, :approved, :picked_up
    )
  end

  def set_reservation
    @r = Reservation.find(params[:id])
  end

  def order_clause
    "date #{params[:old] ? 'DESC' : 'ASC'}, table_id"
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def display_date(date, reservations)
    if !reservations.all?(&:approved?)
      "#{date} <span style='font-style: italic; color: red'>!</span>".html_safe
    else
      date
    end
  end
end

app/views/reservations/_form.html.haml
= form_for @r, html: { class: '' } do |f|
  - if f.object.errors.any?
    - f.object.errors.full_messages.each do |msg|
      .alert.alert-danger.col-xs-12= msg
  #wrong-table.alert.alert-danger.col-xs-12{ style: 'display: none;' } Stolik zarezerwowany lub ma za mało miejsc
  .form-group.col-xs-12
    .input-group
      .input-group-addon= f.label :table_id, t('.table_id')
      = f.select :table_id, options_from_collection_for_select(Table.all, :id, :number, @r.table_id), {}, { class: 'selectpicker form-control' }
  .form-group.col-xs-12
    .input-group
      .input-group-addon= f.label :date, t('.date')
      = f.date_field :date, class: 'form-control'
  .form-group.col-xs-12
    .input-group
      .input-group-addon= f.label :hour, t('.hour')
      = f.text_field :hour, size: 5, class: 'form-control'
  .form-group.col-xs-12
    .input-group
      .input-group-addon= f.label :people, t('.people')
      = f.number_field :people, min: 1, class: 'form-control'
  .form-group.col-xs-12
    .input-group
      .input-group-addon= f.label :client_name, user_signed_in? ? t('.client_name') : t('.client_name2')
      = f.text_field :client_name, class: 'form-control'
  .form-group.col-xs-12
    .input-group
      .input-group-addon= f.label :client_phone, user_signed_in? ? t('.client_phone') : t('.client_phone2')
      = f.text_field :client_phone, size: 10, class: 'form-control'
  .form-group.col-xs-12
    = f.hidden_field :approved, value: user_signed_in? ? true : false
    = f.submit t('.submit'), class: 'btn btn-success btn-block'

app/views/reservations/_reservations.html.haml
- all_reservations.each do |date, reservations|
  .panel.panel-primary
    .panel-heading.reservations
      %h3.panel-title= display_date(date, reservations)
    %table.table.table-striped.reservations
      %thead
        %tr
          %th= t('.hour')
          %th= t('.name')
          %th= t('.phone')
          %th= t('.table')
          %th= t('.people')
          %th= t('.picked_up')
          %th= t('.manage')
      %tbody
        - reservations.each do |reservation|
          - next if reservation.table.nil? && current
          %tr{ class: "#{'cancelled' if reservation.deleted?}" }
            %td
              = reservation.hour
              %span{ style: 'font-style: italic; color: red'}= '!' unless reservation.approved?
            %td= reservation.client_name
            %td= reservation.client_phone
            %td= reservation.table ? reservation.table.number : Table.with_deleted.find(reservation.table_id).number
            %td= reservation.people
            %td= reservation.picked_up? ? glyph('', 'ok') : glyph('', 'remove')
            %td
              - if can?(:manage, reservation) && reservation.deleted?
                = link_to glyph('', 'list-alt'), '#', class: 'show-note', title: reservation.cancel_reason
              - if can?(:update, reservation) && !reservation.approved? && !reservation.deleted? && current
                = link_to glyph('', 'ok'), reservation_path(reservation.id, reservation: { approved: true }), method: :put, title: t('.approve'), data: { no_turbolink: true }
              - if can?(:update, reservation) && !reservation.picked_up? && reservation.approved? && !reservation.deleted? && current
                = link_to glyph('', 'thumbs-up'), reservation_path(reservation.id, reservation: { picked_up: true }), method: :put, title: t('.marked_as_pick'), data: { no_turbolink: true }
              - if can?(:edit, reservation) && !reservation.deleted? && current
                = link_to glyph('', 'pencil'), edit_reservation_path(reservation.id), title: t('.edit')
              - if can?(:destroy, reservation) && !reservation.deleted? && current
                = link_to glyph('', 'remove'), note_reservation_path(reservation.id), title: t('.cancel')

app/views/reservations/check.html.haml
#container
  - if request.get?
    .row
      .col-xs-12
        %h1 Sprawdź swoją rezerwację
    .row
      .col-xs-12.form
        = form_tag(reservations_check_path, method: :post) do
          .form-group.col-xs-12
            .input-group
              .input-group-addon= label_tag 'client_name', 'Imię i nazwisko'
              = text_field_tag 'client_name', '', autofocus: true, class: 'form-control'
          .form-group.col-xs-12
            .input-group
              .input-group-addon= label_tag 'client_phone', 'Numer telefonu'
              = text_field_tag 'client_phone', '', class: 'form-control'
          .form-group.col-xs-12
            = submit_tag 'Szukaj', class: 'btn btn-success btn-block'
  - else
    - if @r.any?
      %h1= @r.many? ? 'Twoje rezerwacje' : 'Twoja rezerwacja'
      - @r.each do |r|
        .row
          .col-xs-12
            %p= "Rezerwacja na nazwisko #{r.client_name}."
            %p= "Stolik nr #{r.table_id}, data: #{r.date}, godzina: #{r.hour}"
            - if r.approved?
              %p{ style: 'color: green; font-weight: bold'} POTWIERDZONA
            - else
              %p{ style: 'color: red; font-weight: bold'} NIEPOTWIERDZONA
    - else
      %h1= "Nie znaleziono rezerwacji na nazwisko #{params[:client_name]}"

app/views/reservations/edit.html.haml
#new-container.row
  .col-xs-12
    #tables-list.well
      - (1..Table.count).each do |i|
        %div{class: "table table-#{i}"}= i

  .row
    .col-xs-12.form
      = render 'form'

app/views/reservations/index.html.haml
.row.header-current
  .col-xs-12
    %p.header-current= (params[:old] ? t('.old') : t('.current'))
    .row
      .col-xs-12
        - if @reservations.any?
          = render partial: 'reservations', locals: { all_reservations: @reservations, current: !params[:old] }
        - else
          .alert.alert-warning Brak rezerwacji

app/views/reservations/new.html.haml
#new-container.row
  .col-xs-12
    #tables-list.well
      - @tables.each do |id, number|
        %div{class: "table table-id-#{id}"}= number

  .row
    .col-xs-12.form
      = render 'form'

app/views/reservations/note.html.haml
#note-container
  = form_tag reservation_path(@r), method: :delete do
    .row
      .form-group.col-xs-12
        = label_tag 'note', 'Podaj powód odwołania rezerwacji'
        = text_area_tag 'note', '', class: 'form-control', rows: 5
    .row
      .form-group.col-xs-6
        = button_tag glyph('SKASUJ', 'exclamation-sign'), class: 'btn btn-danger btn-block'
      .form-group.col-xs-6
        = link_to glyph('Wróć', 'circle-arrow-left'), reservations_path, class: 'btn btn-primary btn-block'