config/routes.rb
Rails.application.routes.draw do
  resources :reservations, except: [:show]
  get 'reservations/:id/note', to: 'reservations#note', as: 'note_reservation'
  match 'reservations/check' => 'reservations#check', via: [:get, :post]

  resources :tables, only: [:index, :create, :update, :destroy]
  get 'tables/restrict' => 'tables#restrict'

  devise_for :users
  get 'users', to: 'users#index', as: 'users'
  post 'create_user', to: 'users#create', as: 'create_user'
  delete 'destroy_user/:id', to: 'users#destroy', as: 'destroy_user'
  post 'promote_user/:id', to: 'users#promote', as: 'promote_user'

  get 'reservations', to: 'reservations#index', as: 'user_root'
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  get '*path' => redirect('/')

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :authenticate_user!, except: [:restrict]

  def index
    @tables = Table.order(:number)
    @table = Table.new
  end

  def create
    @table = Table.new(table_parameters)

    if @table.save
      flash[:notice] = 'Utworzono stolik'
    else
      flash[:alert] = 'Wystąpił problem podczas tworzenia stolika'
    end
    respond_to do |format|
      format.html { redirect_to tables_path }
    end
  end

  def update
    table = Table.find(params[:id])
    table.seats = params[:seats]

    respond_to do |format|
      if table.save
        format.json { render json: { message: 'success'} }
      else
        format.json { render json: { message: 'error'} }
      end
    end
  end

  def destroy
    table = Table.find(params[:id])

    if table.destroy
      flash[:notice] = 'Pomyślnie usunięto stolik'
    else
      flash[:alert] = 'Wystąpił błąd przy usuwaniu stolika'
    end
    respond_to do |format|
      format.html { redirect_to tables_path }
    end
  end

  def restrict
    respond_to do |format|
      date_ids = Table.ids_by_date(params[:date], params[:id])
      people_ids = Table.ids_by_people(params[:people])
      format.json { render json: date_ids & people_ids }
    end
  end

  private

  def table_parameters
    params.require(:table).permit(:number, :seats)
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/index.html.haml
#container
  .panel.panel-primary
    .panel-heading
      .panel-title= t('.manage')
    %table.table.table-striped
      %thead
        %tr
          %th= t('.number')
          %th= t('.seats')
          %th= t('all.manage')
      %tbody
        - @tables.each do |table|
          %tr
            %td= table.number
            %td.hidden.input-seats= number_field_tag "seats_#{table.id}", table.seats
            %td
              = table.seats
              %span.pull-right.msg= ''
            %td
              = link_to glyph('', 'pencil'), '#', class: 'edit-table', title: t('all.edit')
              = link_to glyph('', 'ok'), '#', class: 'save-table hidden', title: t('all.save')
              = link_to glyph('', 'remove'), table_path(table.id), class: 'remove-table', method: :delete, title: t('all.remove'), data: { confirm: t('all.sure') }

%h2= t('.add_new')

= form_for @table do |f|
  - if f.object.errors.any?
    - f.object.errors.full_messages.each do |msg|
      .alert.alert-danger.col-xs-12= msg
  .form-group.col-xs-4
    .input-group
      .input-group-addon= f.label :number, t('.number')
      = f.number_field :number, min: 1, class: 'form-control'
  .form-group.col-xs-4
    .input-group
      .input-group-addon= f.label :seats, t('.seats')
      = f.number_field :seats, min: 1, class: 'form-control'
  .form-group.col-xs-4
    = f.submit t('.submit'), class: 'btn btn-success btn-block'