config/routes.rb
Rails.application.routes.draw do
  resources :reservations, except: [:show]
  get 'reservations/:id/note', to: 'reservations#note', as: 'note_reservation'
  match 'reservations/check' => 'reservations#check', via: [:get, :post]

  resources :tables, only: [:index, :create, :update, :destroy]
  get 'tables/restrict' => 'tables#restrict'

  devise_for :users
  get 'users', to: 'users#index', as: 'users'
  post 'create_user', to: 'users#create', as: 'create_user'
  delete 'destroy_user/:id', to: 'users#destroy', as: 'destroy_user'
  post 'promote_user/:id', to: 'users#promote', as: 'promote_user'

  get 'reservations', to: 'reservations#index', as: 'user_root'
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  get '*path' => redirect('/')

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "RezerwApka" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <% if user_signed_in? %>
            <%= link_to 'RezerwApka', user_root_path, class: 'navbar-brand' %>
          <% else %>
            <%= link_to 'RezerwApka', root_path, class: 'navbar-brand' %>
          <% end %>
        </div>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to t('.current'), reservations_path, class: 'active' if can? :read, Reservation %></li>
            <li><%= link_to t('.old'), reservations_path(old: true) if can? :manage, Reservation %></li>
            <li><%= link_to t('.new'), new_reservation_path if can? :create, Reservation %></li>
            <li><%= link_to t('.tables'), tables_path if can? :manage, Table %></li>
            <li><%= link_to t('.users'), users_path if can? :manage, User %></li>
          <% else %>
            <li><%= link_to t('.new2'), new_reservation_path if can? :create, Reservation %></li>
            <li><%= link_to t('.check'), reservations_check_path if can? :check, Reservation %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to t('.change_password'), edit_user_registration_path %></li>
          <li><%= link_to t('.logout'), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to t('.login'), new_user_session_path %></li>
        <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if flash.key? :notice %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash.key? :alert %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>